version: 2
registries:
  github-ci4rail:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.FW_CI_TOKEN}}

updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    registries:
      - github-ci4rail
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
