#
name: Build in different environments
on:
  push:
    branches:
      - main
      - initial

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build in Container
        run: |
          cat << EOF > /tmp/cmd.sh
          #!/bin/sh
          set -e
          apt-get update && export DEBIAN_FRONTEND=noninteractive \
            && apt-get -y install --no-install-recommends gcc g++ git automake libtool \
            make cmake pkg-config libprotobuf-dev libprotoc-dev protobuf-compiler \
            ca-certificates

          git clone https://github.com/protobuf-c/protobuf-c.git && \
            cd protobuf-c && ./autogen.sh && ./configure && make && make install
          cd /repo
          mkdir build && cd build
          cmake ..
          cmake --build
          cmake --install

          EOF

          pwd
          ls -l
          ls -l `pwd`

          chmod +x /tmp/cmd.sh
          docker run --platform linux/amd64 -v`pwd`:/repo -v/tmp:/cmd ubuntu:latest ls /cmd/cmd.sh
